services:
  - type: web
    name: newrustacean.com
    runtime: static
    buildCommand: 'make all'
    envVars:
    - key: RUSTUP_HOME
      value: '/tmp'
    pullRequestPreviewsEnabled: true
    staticPublishPath: 'target/doc'
    domain: newrustacean.com
