(function() {var implementors = {};
implementors["show_notes"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e002/struct.Circle.html\" title=\"struct show_notes::e002::Circle\">Circle</a>",synthetic:false,types:["show_notes::e002::Circle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e003/struct.PreexistingStruct.html\" title=\"struct show_notes::e003::PreexistingStruct\">PreexistingStruct</a>",synthetic:false,types:["show_notes::e003::PreexistingStruct"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"show_notes/e003/enum.RelatedishThings.html\" title=\"enum show_notes::e003::RelatedishThings\">RelatedishThings</a>",synthetic:false,types:["show_notes::e003::RelatedishThings"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e009/struct.DoubleAndOne.html\" title=\"struct show_notes::e009::DoubleAndOne\">DoubleAndOne</a>",synthetic:false,types:["show_notes::e009::DoubleAndOne"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e019/struct.ANoCopyOrClonePoint.html\" title=\"struct show_notes::e019::ANoCopyOrClonePoint\">ANoCopyOrClonePoint</a>",synthetic:false,types:["show_notes::e019::ANoCopyOrClonePoint"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e019/struct.BJustClonePoint.html\" title=\"struct show_notes::e019::BJustClonePoint\">BJustClonePoint</a>",synthetic:false,types:["show_notes::e019::BJustClonePoint"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e019/struct.CCopyPoint.html\" title=\"struct show_notes::e019::CCopyPoint\">CCopyPoint</a>",synthetic:false,types:["show_notes::e019::CCopyPoint"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e021/struct.EmailStruct.html\" title=\"struct show_notes::e021::EmailStruct\">EmailStruct</a>",synthetic:false,types:["show_notes::e021::EmailStruct"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
